---
- name: install urllib3
  pip:
    name: urllib3
    version: 1.7.1
- name: install pyasn1
  pip:
    name: pyasn1
    version: 0.3.7
- name: install pyOpenSSL
  pip:
    name: pyOpenSSL
    version: 0.13
- name: install ndg-httpsclient
  pip:
    name: ndg-httpsclient
    version: 0.4.3
- name: Install https for apt (Ubuntu)
  apt: name=apt-transport-https state=present

- name: Get Icinga2 Apt Key for Debian OS family
  apt_key: url={{ icinga2_key }}
           state=present

- name: Get Icinga2 Apt Repos for Debian OS family
  apt_repository: repo='{{ item.repo }}'
                  update_cache=yes
                  state=present
  with_items: '{{ icinga2_deb_repos }}'

- name: Install Icinga2 on Debian OS family
  apt: pkg={{ item.package }}
       update_cache=yes
       install_recommends=no
       force=yes
  with_items: '{{ icinga2_ubuntu_pkg }}'
  when: icinga2_install == 'standard'

# - name: Install Icinga2 Deps on Debian OS family
#   apt: pkg={{ item.package }}
#        update_cache=yes
#        install_recommends=no
#        force=yes
#   with_items: '{{ icinga2_ubuntu_custom_pkg }}'
#   when: icinga2_install == 'custom'

# - name: List deb files for installation
#   find:
#     paths=/opt/icinga2
#     file_type=file
#     patterns='*.deb'
#     recurse=yes
#   register: icinga2_custom_deb_items
#   when: icinga2_install == 'custom'

# - name: Install CUSTOM Icinga2 on Debian OS family
#   apt: deb={{ item.path }}
#        force=yes
#   with_items: '{{ icinga2_custom_deb_items.files }}'
#   when: icinga2_install == 'custom'

- name: Remove ansible dependencies using apt
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - icinga2
    - icinga2-bin
    - icinga2-classicui
    - icinga2-common
    - icinga2-dbg
    - icinga2-doc
    - icinga2-ido-mysql
    - icinga2-ido-pgsql
    - icinga2-studio
    - libicinga2
    - vim-icinga2
    - apache2-utils
    - nagios-plugins
    - bsd-mailx
    - gdebi
  when: icinga2_install == 'custom'

# - name: cleanup/fix installations
#   shell: apt-get -f install -y
#   when: icinga2_install == 'custom'

# - name: remove all dependencies and icinga
#   shell: apt-get remove icinga2 icinga2-bin icinga2-classicui icinga2-common icinga2-dbg icinga2-doc icinga2-ido-mysql icinga2-ido-pgsql icinga2-studio libicinga2 vim-icinga2 apache2-utils nagios-plugins bsd-mailx gdebi -y
#   when: icinga2_install == 'custom'

- name: cleanup/fix installations
  shell: apt-get -f install -y
  when: icinga2_install == 'custom'

- name: remove broken installation leftovers
  shell: apt-get autoremove -y
  when: icinga2_install == 'custom'

- name: install gdebi
  apt: pkg=gdebi
       install_recommends=no
  when: icinga2_install == 'custom'

- name: install (via gdebi) common
  shell: gdebi /opt/icinga2/icinga2-common_2.8.4-2wk_all.deb -n
  when: icinga2_install == 'custom'

- name: install (via gdebi) libicinga2
  shell: gdebi /opt/icinga2/libicinga2_2.8.4-2wk_amd64.deb -n
  when: icinga2_install == 'custom'

- name: install (via gdebi) bin
  shell: gdebi /opt/icinga2/icinga2-bin_2.8.4-2wk_amd64.deb -n
  when: icinga2_install == 'custom'

- name: install (via gdebi) icinga
  shell: gdebi /opt/icinga2/icinga2_2.8.4-2wk_amd64.deb -n
  when: icinga2_install == 'custom'

# - name: install (via gdebi) icinga-ido-mysql
#   # shell: gdebi /opt/icinga2/icinga2-ido-mysql_2.8.4-2wk_amd64.deb -n
#   apt: deb=/opt/icinga2/icinga2-ido-mysql_2.8.4-2wk_amd64.deb
#        force=yes
#   when: icinga2_install == 'custom'

- name: Start Icinga2
  service: name=icinga2
           state=started
           enabled=yes
  ignore_errors: yes
